apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mc-join
  namespace: kasten-io
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: kasten-secrets-store
    kind: ClusterSecretStore
  target:
    name: mc-join
  data:
  - secretKey: token
    remoteRef:
      key: prod/kasten/mc-join
      property: token
  - secretKey: endpoint
    remoteRef:
      key: prod/kasten/mc-join
      property: endpoint