apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kasten-resources-app-set
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-kasten-resources'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/mattbator/kasten-gitops/
        targetRevision: HEAD
        path: apps/kasten-resources
      destination:
        server: '{{.server}}'
        namespace: kasten-io
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

