apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-resources-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kasten-io
    server: {{ .Values.spec.destination.server }}
  source:
    path: apps/kasten-resources
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: {{ .Values.spec.project }}
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true